cabal-version: 3.0
name: day1
version: 1.0.0.0

common defaults
  ghc-options: -Wall
  default-language: Haskell2010

library
  import: defaults
  hs-source-dirs: lib
  exposed-modules: Utils
  build-depends: base ^>=4.18.3.0

executable puzzle1
  import: defaults
  main-is: Puzzle1.hs
  build-depends:
    base ^>=4.18.3.0,
    day1,

executable puzzle2
  import: defaults
  main-is: Puzzle2.hs
  build-depends:
    base ^>=4.18.3.0,
    day1,

test-suite test
  import: defaults
  type: exitcode-stdio-1.0
  hs-source-dirs: tests
  main-is: Spec.hs
  build-depends:
    base ^>=4.18.3.0,
    day1,
    hspec,
